modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="the_eom_mod"
version="1.0.0"
displayName="The EoM Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="abnor, MCreator"

[[dependencies.the_eom_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




